### ISSUE TITLE
Extension claims webplayer not running

### ISSUE THREAD

**Issue by MykStreja** [davidnguyen11/spotify-extension-landing-page#6]
Extension claims webplayer not running while I am listening to Spotify on the webplayer. Tried dis/enabling the extension, no change. Running on Linux 21 and Firefox 112. I closed the Spotify window, then opened a new instance of Spotify, now I'm locked out of Spotify.

Update: I uninstalled the extension, upgraded Firefox to v113, closed Firefox, then restarted my computer. Reopened Firefox, reinstalled the extension, opened Spotify webplayer ... and it all works. So, the issue is no longer critical, but maybe there's something that needs addressing? Let me know how I can help, because this is really a useful gadget.

**Comment by davidnguyen11** [comment]
Hey thanks @MykStreja to raise this concern. That something I can't control, modern browsers have mechanism to deactivate the tabs if they're idle. When it's deactivated, the connection between Client App and Streaming server is cut. That's why you can't control your Web App Spotify with Spotify Extension.
